// "Madam ki Class: Table Edition", Rooms 1 to 9. One sitcom format, a new problem each night.
// Every episode: a problem at the table (with a prop) -> Ayesha goes quiet -> Madam -> someone panics -> she scolds
// the one who messed up -> a school punishment (cold open) -> someone objects, gets the glare, backs down ->
// the riddle as her "saza" -> the friends nearly solve it -> "Chup!" -> she tells the viewer: DM only ->
// glasses off, sweet line -> end card: send it to a named friend.
// `say` is on screen (Roman Urdu, *accent*); `hi` is what the voice reads. Never "pehle dekho" before launch.

const BURGER = `<svg class="big" viewBox="0 0 70 50"><ellipse cx="35" cy="14" rx="31" ry="13" fill="#e0a04a"/><rect x="4" y="20" width="62" height="5" rx="2" fill="#e7c341"/><rect x="3" y="24" width="64" height="9" rx="4" fill="#5a2d17"/><rect x="2" y="32" width="66" height="5" rx="2" fill="#6ea34a"/><rect x="4" y="36" width="62" height="4" rx="2" fill="#c8402b"/><rect x="6" y="39" width="58" height="10" rx="5" fill="#e0a04a"/></svg><div class="price">"Jumbo" burger</div>`;
const L = (id, who, say, hi) => ({ id, who, say, hi });
const DM = L('fourth', 'madam', 'Aur tum... answer sirf *DM* mein. 4 October ke baad.', 'और तुम... आंसर सिर्फ़ डीएम में। चार अक्टूबर के बाद।');
const CHUP = L('chup', 'madam', '*Chup!*', 'चुप!');

export const EPISODES = {
  'escape-01-the-photo': {
    room: 'Room 1', holder: 'zain', victim: 'zain', panicker: 'hamza', objector: 'sara', solvers: ['zain', 'hamza'], punish: 'stand',
    prop: { label: 'Menu photo', html: BURGER },
    headline: 'Har group mein ek *Ayesha* hoti hai',
    cta: { big: 'Apne group ki *Ayesha* ko bhejo.', small: 'Escape the menu, Room 1. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'zain', 'Bhai... menu pe ye *jumbo* tha.', 'भाई... मेन्यू पे ये जंबो था।')],
    panic: L('panic', 'hamza', 'Nahi nahi nahi! Ayesha, *phir se nahi!*', 'नहीं नहीं नहीं! आयशा, फिर से नहीं!'),
    scoldA: L('scoldA', 'madam', 'Menu ki photo pe *bharosa* kiya?', 'मेन्यू की फ़ोटो पे भरोसा किया?'),
    scoldB: L('scoldB', 'madam', 'Bench pe *khade* ho jao!', 'बेंच पे खड़े हो जाओ!'),
    object: L('object', 'sara', 'Yaar chup kar, *log dekh rahe hain!*', 'यार चुप कर, लोग देख रहे हैं!'),
    back: L('back', 'sara', '...main to bas *keh rahi thi.*', '...मैं तो बस कह रही थी।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna bill tumhara!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना बिल तुम्हारा!'),
    read: [L('read', 'madam', 'Market jahan shopping kam, *gol gappay zyada.* Pehla letter!', 'मार्केट जहाँ शॉपिंग कम, गोलगप्पे ज़्यादा। पहला लेटर!')],
    try1: L('try1', 'zain', 'Gol gappay wali market... *wo to...*', 'गोलगप्पे वाली मार्केट... वो तो...'),
    try2: L('try2', 'hamza', 'Mujhe pata hai! *Pehla letter...*', 'मुझे पता है! पहला लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Kya hua? Khana *thanda* ho raha hai.', 'क्या हुआ? खाना ठंडा हो रहा है।'),
  },
  'escape-02-chefs-special': {
    room: 'Room 2', holder: 'hamza', victim: 'zain', panicker: 'sara', objector: 'hamza', solvers: ['sara', 'zain'], punish: 'duck',
    prop: { label: 'Menu, page 11', html: `<div class="rows"><div><b>Chef's special</b></div><div>House platter</div><div>Signature something</div><div>"Ask your server"</div></div>` },
    headline: 'Jab koi *"chef\'s special"* bina pooche mangwa le',
    cta: { big: 'Us dost ko bhejo jo har jagah *chef\'s special* mangwata hai.', small: 'Escape the menu, Room 2. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'hamza', 'Chef\'s special... *hai kya ye?*', 'शेफ़्स स्पेशल... है क्या ये?'), L('s2', 'zain', 'Mangwa lo, *dekh lenge.*', 'मंगवा लो, देख लेंगे।')],
    panic: L('panic', 'sara', 'Ayesha nahi! *Dinner hai ye, class nahi!*', 'आयशा नहीं! डिनर है ये, क्लास नहीं!'),
    scoldA: L('scoldA', 'madam', 'Bina jaane order? *Sirf naam pe?*', 'बिना जाने ऑर्डर? सिर्फ़ नाम पे?'),
    scoldB: L('scoldB', 'madam', '*Murga* ban jao!', 'मुर्गा बन जाओ!'),
    object: L('object', 'hamza', 'Yaar, *waiter dekh raha hai!*', 'यार, वेटर देख रहा है!'),
    back: L('back', 'hamza', '...main to menu *parh raha tha.*', '...मैं तो मेन्यू पढ़ रहा था।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna dessert cancel!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना डेज़र्ट कैंसल!'),
    read: [L('read', 'madam', 'Sunday subah ka asli nashta. *Chanay saath.* Pehla letter!', 'संडे सुबह का असली नाश्ता। चने साथ। पहला लेटर!')],
    try1: L('try1', 'sara', 'Sunday wala nashta... *wo to...*', 'संडे वाला नाश्ता... वो तो...'),
    try2: L('try2', 'zain', 'Mujhe pata hai! *Pehla letter...*', 'मुझे पता है! पहला लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Chef\'s special aa gaya? *Yay!*', 'शेफ़्स स्पेशल आ गया? ये!'),
  },
  'escape-03-group-chat': {
    room: 'Room 3', holder: 'sara', victim: 'zain', panicker: 'hamza', objector: 'sara', solvers: ['hamza', 'sara'], punish: 'out',
    prop: { label: 'Khana kahan? (6)', html: `<div class="chat"><p>kahin bhi chalo</p><p>koi pic bhejo</p><p class="me">jo tu le</p><p>142 unread</p></div>` },
    headline: 'Har group chat ka *ek hi anjaam*',
    cta: { big: 'Apne *group chat* mein bhejo. Abhi.', small: 'Escape the menu, Room 3. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'sara', 'Do ghante discussion... *aur order wohi purana.*', 'दो घंटे डिस्कशन... और ऑर्डर वही पुराना।'), L('s2', 'zain', 'Main ne to kaha tha, *jo tu le.*', 'मैंने तो कहा था, जो तू ले।')],
    panic: L('panic', 'hamza', 'Ayesha... *please, aaj nahi!*', 'आयशा... प्लीज़, आज नहीं!'),
    scoldA: L('scoldA', 'madam', '"Jo tu le"? *Ye koi jawab hai?*', 'जो तू ले? ये कोई जवाब है?'),
    scoldB: L('scoldB', 'madam', 'Class se *bahar!*', 'क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *restaurant hai ye!*', 'यार, रेस्टोरेंट है ये!'),
    back: L('back', 'sara', '...theek hai, *main chup.*', '...ठीक है, मैं चुप।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna agla plan tum banao ge!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना अगला प्लान तुम बनाओगे!'),
    read: [L('read', 'madam', 'Raat bhar pakte hain, subah *naan* ke saath. Pehla letter!', 'रात भर पकते हैं, सुबह नान के साथ। पहला लेटर!')],
    try1: L('try1', 'hamza', 'Raat bhar pakte hain... *wo to...*', 'रात भर पकते हैं... वो तो...'),
    try2: L('try2', 'sara', 'Mujhe pata hai! *Pehla letter...*', 'मुझे पता है! पहला लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'To... *next week* kahan chalein?', 'तो... नेक्स्ट वीक कहाँ चलें?'),
  },
  'escape-04-portion': {
    room: 'Room 4', holder: 'hamza', victim: 'hamza', panicker: 'zain', objector: 'zain', solvers: ['sara', 'zain'], punish: 'stand',
    prop: { label: 'Order', html: `<div class="rows"><div><b>3 x</b> Family platter</div><div>For: 4 log</div><div>Size: pata nahi</div></div>` },
    headline: 'Jab koi *andaze* se order kare',
    cta: { big: 'Us dost ko bhejo jo hamesha *zyada* order karta hai.', small: 'Escape the menu, Room 4. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'hamza', 'Ek plate chaar logon ki thi... *main ne teen mangwayin.*', 'एक प्लेट चार लोगों की थी... मैंने तीन मंगवाईं।'), L('s2', 'sara', 'Ab ye khana *kaun khayega?*', 'अब ये खाना कौन खाएगा?')],
    panic: L('panic', 'zain', 'Ayesha... *chashma wapas rakho!*', 'आयशा... चश्मा वापस रखो!'),
    scoldA: L('scoldA', 'madam', 'Plate ka size *pata tha?* Andaza lagaya?', 'प्लेट का साइज़ पता था? अंदाज़ा लगाया?'),
    scoldB: L('scoldB', 'madam', 'Khade ho jao! *Ginti karo!*', 'खड़े हो जाओ! गिनती करो!'),
    object: L('object', 'zain', 'Yaar, bach jayega, *ghar le jayenge!*', 'यार, बच जाएगा, घर ले जाएँगे!'),
    back: L('back', 'zain', '...bas *keh raha tha.*', '...बस कह रहा था।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna saara bill tumhara!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना सारा बिल तुम्हारा!'),
    read: [L('read', 'madam', 'Fort Road ki gali, *Badshahi Masjid* ke saamne. Doosre lafz ka chautha letter!', 'फ़ोर्ट रोड की गली, बादशाही मस्जिद के सामने। दूसरे लफ़्ज़ का चौथा लेटर!')],
    try1: L('try1', 'sara', 'Fort Road ki gali... *wo to...*', 'फ़ोर्ट रोड की गली... वो तो...'),
    try2: L('try2', 'zain', 'Mujhe pata hai! *Doosra lafz...*', 'मुझे पता है! दूसरा लफ़्ज़...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', '*Doggy bag* mangwa lein?', 'डॉगी बैग मंगवा लें?'),
  },
  'escape-05-sab-acha-hai': {
    room: 'Room 5', holder: null, victim: 'zain', panicker: 'hamza', objector: 'sara', solvers: ['hamza', 'sara'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Waiter se poocho *kya acha hai...*',
    cta: { big: 'Us dost ko bhejo jo *"sab acha hai"* pe maan jata hai.', small: 'Escape the menu, Room 5. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'zain', 'Bhai, yahan *acha kya hai?*', 'भाई, यहाँ अच्छा क्या है?'), L('s2', 'waiter', 'Sir, *sab acha hai.*', 'सर, सब अच्छा है।'), L('s3', 'zain', 'Theek hai, *sab le aao.*', 'ठीक है, सब ले आओ।')],
    panic: L('panic', 'hamza', 'Uh oh. *Chashma nikal raha hai.*', 'अह ओह। चश्मा निकल रहा है।'),
    scoldA: L('scoldA', 'madam', '"Sab acha hai" *maan liya?*', 'सब अच्छा है, मान लिया?'),
    scoldB: L('scoldB', 'madam', 'Class se *bahar!*', 'क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *waiter ki galti hai!*', 'यार, वेटर की ग़लती है!'),
    back: L('back', 'sara', '...haan, *meri bhi.*', '...हाँ, मेरी भी।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna tip tum do ge!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना टिप तुम दोगे!'),
    read: [L('read', 'madam', 'Daal, gandum, gosht, aur *ghanton ka ghota.* Pehla letter!', 'दाल, गंदुम, गोश्त, और घंटों का घोटा। पहला लेटर!')],
    try1: L('try1', 'hamza', 'Ghanton ka ghota... *wo to...*', 'घंटों का घोटा... वो तो...'),
    try2: L('try2', 'sara', 'Mujhe pata hai! *Pehla letter...*', 'मुझे पता है! पहला लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Sab acha hai *na?*', 'सब अच्छा है ना?'),
  },
  'escape-06-wo-wala': {
    room: 'Room 6', holder: 'zain', victim: 'zain', panicker: 'sara', objector: 'hamza', solvers: ['sara', 'hamza'], punish: 'duck',
    prop: { label: 'Us table pe', html: `<div class="huge">&rarr; ?</div><div class="price">"Wo wala"</div>` },
    headline: 'Jab dost *doosri table* ki taraf ishara kare',
    cta: { big: 'Us dost ko bhejo jo har baar *"wo wala"* mangwata hai.', small: 'Escape the menu, Room 6. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'zain', 'Mujhe *wo wala* chahiye. Jo us table pe gaya.', 'मुझे वो वाला चाहिए। जो उस टेबल पे गया।'), L('s2', 'hamza', 'Naam kya hai *uska?*', 'नाम क्या है उसका?'), L('s3', 'zain', '...wo *wala.*', '...वो वाला।')],
    panic: L('panic', 'sara', 'Ayesha, bas *ungli neeche karwa do!*', 'आयशा, बस उंगली नीचे करवा दो!'),
    scoldA: L('scoldA', 'madam', 'Ajnabi ki plate pe ungli? *Naam tak nahi pata?*', 'अजनबी की प्लेट पे उंगली? नाम तक नहीं पता?'),
    scoldB: L('scoldB', 'madam', '*Murga* ban jao!', 'मुर्गा बन जाओ!'),
    object: L('object', 'hamza', 'Yaar, *sab hi karte hain!*', 'यार, सब ही करते हैं!'),
    back: L('back', 'hamza', '...main *nahi karta.*', '...मैं नहीं करता।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna wo wala bhi cancel!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना वो वाला भी कैंसल!'),
    read: [L('read', 'madam', 'Paani, imli, chanay. *Ek bite,* poora dhamaka. Pehle lafz ka doosra letter!', 'पानी, इमली, चने। एक बाइट, पूरा धमाका। पहले लफ़्ज़ का दूसरा लेटर!')],
    try1: L('try1', 'sara', 'Ek bite, poora dhamaka... *wo to...*', 'एक बाइट, पूरा धमाका... वो तो...'),
    try2: L('try2', 'hamza', 'Mujhe pata hai! *Doosra letter...*', 'मुझे पता है! दूसरा लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Chalo, *wo wala* hi mangwa lete hain.', 'चलो, वो वाला ही मंगवा लेते हैं।'),
  },
  'escape-07-the-stare': {
    room: 'Room 7', holder: 'sara', victim: 'hamza', panicker: 'zain', objector: 'sara', solvers: ['zain', 'sara'], punish: 'out',
    prop: { label: 'Waiting since', html: `<div class="huge">40:00</div><div class="price">minutes</div>` },
    headline: 'Har group mein ek banda *40 minute* menu parhta hai',
    cta: { big: 'Us dost ko bhejo jo *40 minute* menu parhta hai.', small: 'Escape the menu, Room 7. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'sara', 'Chaalees minute ho gaye... *order karo!*', 'चालीस मिनट हो गए... ऑर्डर करो!'), L('s2', 'hamza', 'Ruko, abhi *page do* pe hoon.', 'रुको, अभी पेज दो पे हूँ।'), L('s3', 'hamza', '...wohi jo *pichli baar* liya tha.', '...वही जो पिछली बार लिया था।')],
    panic: L('panic', 'zain', 'Oh no. *Exam hall mode.*', 'ओह नो। एग्ज़ाम हॉल मोड।'),
    scoldA: L('scoldA', 'madam', 'Chaalees minute parha, aur likha *wohi purana?*', 'चालीस मिनट पढ़ा, और लिखा वही पुराना?'),
    scoldB: L('scoldB', 'madam', 'Class se *bahar!*', 'क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *usko wohi pasand hai!*', 'यार, उसको वही पसंद है!'),
    back: L('back', 'sara', '...theek hai, *nahi pasand.*', '...ठीक है, नहीं पसंद।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna agli baar sab se aakhir mein order!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना अगली बार सबसे आख़िर में ऑर्डर!'),
    read: [L('read', 'madam', 'Chawal aur doodh ki dosti. Shaadi mein *sab se pehle* khatam. Teesra letter!', 'चावल और दूध की दोस्ती। शादी में सबसे पहले ख़त्म। तीसरा लेटर!')],
    try1: L('try1', 'zain', 'Shaadi mein sab se pehle... *wo to...*', 'शादी में सबसे पहले... वो तो...'),
    try2: L('try2', 'sara', 'Mujhe pata hai! *Teesra letter...*', 'मुझे पता है! तीसरा लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Main bhi wohi lungi jo *pichli baar.*', 'मैं भी वही लूँगी जो पिछली बार।'),
  },
  'escape-08-regret': {
    room: 'Room 8', holder: 'zain', victim: 'zain', panicker: 'hamza', objector: 'sara', solvers: ['hamza', 'zain'], punish: 'duck',
    prop: { label: 'Table 7', html: `<div class="rows"><div>Mystery platter <b>1</b></div><div>Expectations <b>high</b></div><div>What arrived <b>?</b></div></div>` },
    headline: 'Jab dost *"mystery platter"* order kare',
    cta: { big: 'Us dost ko bhejo jo har jagah *mystery* order karta hai.', small: 'Escape the menu, Room 8. Code DM karo, 4 October ke baad. Pehle 5 ka dinner humari taraf se.' },
    setup: [L('s1', 'zain', '"Mystery platter" *mangwaya tha...*', 'मिस्ट्री प्लैटर मंगवाया था...'), L('s2', 'sara', 'Aur mystery *abhi tak hal nahi hui.*', 'और मिस्ट्री अभी तक हल नहीं हुई।')],
    panic: L('panic', 'hamza', 'Ayesha, *kal aakhri din hai, aaj chhod do!*', 'आयशा, कल आख़िरी दिन है, आज छोड़ दो!'),
    scoldA: L('scoldA', 'madam', 'Naam dekh ke mystery? *Bina dekhe?*', 'नाम देख के मिस्ट्री? बिना देखे?'),
    scoldB: L('scoldB', 'madam', '*Murga* ban jao!', 'मुर्गा बन जाओ!'),
    object: L('object', 'sara', 'Yaar, *adventure tha!*', 'यार, एडवेंचर था!'),
    back: L('back', 'sara', '...bura *adventure tha.*', '...बुरा एडवेंचर था।'),
    saza: L('saza', 'madam', 'Saza milegi. Sawal solve karo, *warna ye platter khatam karo!*', 'सज़ा मिलेगी। सवाल सॉल्व करो, वरना ये प्लैटर ख़त्म करो!'),
    read: [L('read', 'madam', 'Bartan bhi yahi, dish ka naam bhi yahi. *Namak* ya tamatar. Pehla letter!', 'बर्तन भी यही, डिश का नाम भी यही। नमक या टमाटर। पहला लेटर!')],
    try1: L('try1', 'hamza', 'Bartan bhi, dish bhi... *wo to...*', 'बर्तन भी, डिश भी... वो तो...'),
    try2: L('try2', 'zain', 'Mujhe pata hai! *Pehla letter...*', 'मुझे पता है! पहला लेटर...'),
    chup: CHUP, fourth: DM,
    sweet: L('sweet', 'ayesha', 'Dessert mein bhi *mystery* mangwayen?', 'डेज़र्ट में भी मिस्ट्री मंगवाएँ?'),
  },
  'escape-09-the-door': {
    room: 'Room 9', holder: 'sara', victim: 'hamza', panicker: 'zain', objector: 'sara', solvers: ['zain', 'hamza'], punish: 'stand', finale: true,
    prop: { label: 'Aaj', html: `<div class="huge">4.10</div><div class="price">aakhri class</div>` },
    headline: 'Aakhri class. *Aaj raat* hunt khulta hai.',
    cta: { big: 'Code complete? *Abhi* DM karo.', small: 'Escape the menu, Room 9. Pehle 5 sahi DM ka dinner humari taraf se. Kal 8:30.' },
    setup: [L('s1', 'sara', 'Aaj *aakhri din* hai.', 'आज आख़िरी दिन है।'), L('s2', 'hamza', 'Nau raat, nau sawal... *aur do letter baaki.*', 'नौ रात, नौ सवाल... और दो लेटर बाक़ी।')],
    panic: L('panic', 'zain', 'Aakhri class. *Sab seedhe baith jao.*', 'आख़िरी क्लास। सब सीधे बैठ जाओ।'),
    scoldA: L('scoldA', 'madam', 'Nau raat se parha rahi hoon. *Ek letter bhi yaad hai?*', 'नौ रात से पढ़ा रही हूँ। एक लेटर भी याद है?'),
    scoldB: L('scoldB', 'madam', 'Khade ho jao! *Aakhri sawal!*', 'खड़े हो जाओ! आख़िरी सवाल!'),
    object: L('object', 'sara', 'Yaar, humein *pata hai jawab!*', 'यार, हमें पता है जवाब!'),
    back: L('back', 'sara', '...*shayad.*', '...शायद।'),
    saza: L('saza', 'madam', 'Do sawal. *Do letter.* Phir code complete.', 'दो सवाल। दो लेटर। फिर कोड कम्प्लीट।'),
    read: [L('read', 'madam', 'Garam, gol gol, *sheeray mein doobi.* Chautha letter!', 'गरम, गोल गोल, शीरे में डूबी। चौथा लेटर!'),
      L('read2', 'madam', 'Chai jismein *paani ki entry band* hai. Pehla letter!', 'चाय जिसमें पानी की एंट्री बंद है। पहला लेटर!')],
    try1: L('try1', 'zain', 'Sheeray mein doobi... *wo to...*', 'शीरे में डूबी... वो तो...'),
    try2: L('try2', 'hamza', 'Aur doodh wali chai... *mujhe pata hai!*', 'और दूध वाली चाय... मुझे पता है!'),
    chup: CHUP,
    fourth: L('fourth', 'madam', 'Aur tum... code complete? *Abhi DM karo.* Pehle paanch jeetenge.', 'और तुम... कोड कम्प्लीट? अभी डीएम करो। पहले पाँच जीतेंगे।'),
    sweet: L('sweet', 'ayesha', 'Kal *8:30.* Sab samajh aa jayega.', 'कल साढ़े आठ। सब समझ आ जाएगा।'),
  },
};
