// Bonus "Madam ki Class: Table Edition" episodes for after launch (5 Oct 2026 onwards), so Madam can name the lesson.
// Guests are ORIGINAL parody types (a food vlogger, etc.), never copies of real people: no real names, faces,
// voices or catchphrases. Claims stay honest: MENVA shows real dishes in 3D at partner restaurants, via the table QR.
const L = (id, who, say, hi) => ({ id, who, say, hi });

export const EXTRAS = {
  'extra-foodie-bhai': {
    room: 'Extra', file: 'table-extra-foodie-bhai', holder: null, burger: true,
    guest: { name: 'Foodie Bhai', seed: 'FoodieBhai', voice: ['hm_psi', 1.08, 1.12], look: { head: ['short5'], skinColor: ['c58c5c'], clothingColor: ['e8a33d'], accessories: ['sunglasses'], accessoriesProbability: 100 } },
    victim: 'guest', panicker: 'sara', objector: 'hamza', solvers: ['zain', 'hamza'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Jab *food vlogger* chakhe baghair review kare',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo *review* dekh ke order karta hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Guys! Aaj hum aaye hain *sab se jumbo* burger pe!', 'गाइज़! आज हम आए हैं सबसे जंबो बर्गर पे!'),
      L('s2', 'guest', 'Size dekho! *Eleven out of ten!*', 'साइज़ देखो! इलेवन आउट ऑफ़ टेन!'),
      L('s3', 'zain', 'Bhai... tu ne *chakha* bhi nahi.', 'भाई... तूने चखा भी नहीं।'),
    ],
    panic: L('panic', 'sara', 'Ayesha, *mehmaan hain, chhod do!*', 'आयशा, मेहमान हैं, छोड़ दो!'),
    scoldA: L('scoldA', 'madam', 'Chakhe baghair *eleven out of ten?*', 'चखे बग़ैर इलेवन आउट ऑफ़ टेन?'),
    scoldB: L('scoldB', 'madam', 'Camera band! *Class se bahar!*', 'कैमरा बंद! क्लास से बाहर!'),
    object: L('object', 'hamza', 'Yaar, uske *followers* hain!', 'यार, उसके फ़ॉलोअर्स हैं!'),
    back: L('back', 'hamza', '...do *sau.*', '...दो सौ।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Review nahi. *Asli plate dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Review nahi. Asli plate dekho. *Order se pehle.*', 'रिव्यू नहीं। असली प्लेट देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'zain', 'Matlab... *table pe asli size?*', 'मतलब... टेबल पे असली साइज़?'),
    try2: L('try2', 'hamza', 'To pehle hi *bata deti!*', 'तो पहले ही बता देती!'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... QR scan karo. *Plate dekho.* Phir order.', 'और तुम... क्यूआर स्कैन करो। प्लेट देखो। फिर ऑर्डर।'),
    sweet: L('sweet', 'ayesha', 'Foodie bhai? Burger *thanda* ho raha hai.', 'फ़ूडी भाई? बर्गर ठंडा हो रहा है।'),
  },
  'extra-har-hafte': {
    room: 'Extra', file: 'table-extra-har-hafte', holder: null,
    victim: 'hamza', panicker: 'hamza', objector: 'sara', solvers: ['zain', 'hamza'], punish: 'duck',
    prop: { label: '', html: '' },
    headline: 'Har hafte *yahi* hota hai',
    rewindText: '20 second pehle...',
    cta: { big: 'Apne group ki *Ayesha* ko bhejo.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'hamza', 'Guys, *pata hai* har hafte kya hota hai?', 'गाइज़, पता है हर हफ़्ते क्या होता है?'),
      L('s2', 'zain', 'Kuch ghalat aata hai. *Ayesha chashma pehenti hai...*', 'कुछ ग़लत आता है। आयशा चश्मा पहनती है...'),
      L('s3', 'sara', '...aur hum log *saza* khaate hain.', '...और हम लोग सज़ा खाते हैं।'),
    ],
    panic: L('panic', 'hamza', 'Aur wo *abhi* ho raha hai.', 'और वो अभी हो रहा है।'),
    scoldA: L('scoldA', 'madam', 'Mere baare mein *reel bana rahe ho?*', 'मेरे बारे में रील बना रहे हो?'),
    scoldB: L('scoldB', 'madam', '*Murga* ban jao!', 'मुर्गा बन जाओ!'),
    object: L('object', 'sara', 'Yaar, reel *pachaas second* ki hai, log skip kar denge!', 'यार, रील पचास सेकंड की है, लोग स्किप कर देंगे!'),
    back: L('back', 'sara', '...tum log *mat karna.*', '...तुम लोग मत करना।'),
    saza: L('saza', 'madam', 'Skip kiya? *Absent!* Aaj ka lesson likho.', 'स्किप किया? एब्सेंट! आज का लेसन लिखो।'),
    lesson: { h: 'Reel poori dekho. *Plate poori dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Reel poori dekho. Plate poori dekho. *Order se pehle.*', 'रील पूरी देखो। प्लेट पूरी देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'zain', 'Ye... *ad hai kya?*', 'ये... ऐड है क्या?'),
    try2: L('try2', 'hamza', 'Haan, *thora sa...*', 'हाँ, थोड़ा सा...'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... jo abhi skip karne wale the. *Share karo.*', 'और तुम... जो अभी स्किप करने वाले थे। शेयर करो।'),
    sweet: L('sweet', 'ayesha', 'Kya? Main to *bas khana dekh rahi thi.*', 'क्या? मैं तो बस खाना देख रही थी।'),
  },
  'extra-budget-baji': {
    room: 'Extra', file: 'table-extra-budget-baji', holder: null, burger: true,
    guest: { name: 'Budget Baji', seed: 'BudgetBaji', voice: ['hf_alpha', 1.12, 1.1], look: { head: ['bun2'], skinColor: ['edb98a'], clothingColor: ['2f5d62'], accessories: ['glasses2'], accessoriesProbability: 100 } },
    victim: 'guest', panicker: 'zain', objector: 'sara', solvers: ['hamza', 'zain'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Jab *budget reviewer* bite gin ke review kare',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo har plate ka *hisaab* lagata hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Hello doston! Aaj ka review: *price per bite!*', 'हेलो दोस्तो! आज का रिव्यू: प्राइस पर बाइट!'),
      L('s2', 'guest', 'Rate dekho, aur burger? *Teen bite* mein khatam!', 'रेट देखो, और बर्गर? तीन बाइट में ख़त्म!'),
      L('s3', 'hamza', 'Baji, aap ne abhi tak *khaya* hi nahi.', 'बाजी, आपने अभी तक खाया ही नहीं।'),
    ],
    panic: L('panic', 'zain', 'Ayesha, *mehmaan hain yaar!*', 'आयशा, मेहमान हैं यार!'),
    scoldA: L('scoldA', 'madam', 'Bite gin rahi ho, *plate dekhi?*', 'बाइट गिन रही हो, प्लेट देखी?'),
    scoldB: L('scoldB', 'madam', 'Calculator band! *Class se bahar!*', 'कैलकुलेटर बंद! क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *hisaab zaroori hai!*', 'यार, हिसाब ज़रूरी है!'),
    back: L('back', 'sara', '...kabhi *kabhi.*', '...कभी कभी।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Rate nahi. *Size dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Rate nahi. Size dekho. *Order se pehle.*', 'रेट नहीं। साइज़ देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'hamza', 'Matlab plate *asli size* mein?', 'मतलब प्लेट असली साइज़ में?'),
    try2: L('try2', 'zain', 'Phir to hisaab *khud hi*...', 'फिर तो हिसाब ख़ुद ही...'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... QR scan karo. *Plate dekho.* Phir order.', 'और तुम... क्यूआर स्कैन करो। प्लेट देखो। फिर ऑर्डर।'),
    sweet: L('sweet', 'ayesha', 'Baji, ek bite *meri taraf se.*', 'बाजी, एक बाइट मेरी तरफ़ से।'),
  },
  'extra-reaction-wala': {
    room: 'Extra', file: 'table-extra-reaction-wala', holder: null, burger: true,
    guest: { name: 'Reaction Wala', seed: 'ReactionWala', voice: ['hm_psi', 1.12, 1.2], look: { head: ['mohawk'], skinColor: ['d08b5b'], clothingColor: ['d97a2b'] } },
    victim: 'guest', panicker: 'hamza', objector: 'zain', solvers: ['sara', 'hamza'], punish: 'duck',
    prop: { label: '', html: '' },
    headline: 'Jab koi *tumhari table* pe live reaction de',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo har cheez pe *react* karta hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Guys! Live reaction: *inka khana aa gaya!*', 'गाइज़! लाइव रिएक्शन: इनका खाना आ गया!'),
      L('s2', 'sara', 'Bhai, tum *hamari table* pe kyun ho?', 'भाई, तुम हमारी टेबल पे क्यों हो?'),
      L('s3', 'guest', 'Content! *Content!*', 'कंटेंट! कंटेंट!'),
    ],
    panic: L('panic', 'hamza', 'Oh no. *Ab do log react karenge.*', 'ओह नो। अब दो लोग रिएक्ट करेंगे।'),
    scoldA: L('scoldA', 'madam', 'Doosron ki plate pe *reaction video?*', 'दूसरों की प्लेट पे रिएक्शन वीडियो?'),
    scoldB: L('scoldB', 'madam', 'Mic band! *Murga ban jao!*', 'माइक बंद! मुर्गा बन जाओ!'),
    object: L('object', 'zain', 'Yaar, *views aa rahe hain!*', 'यार, व्यूज़ आ रहे हैं!'),
    back: L('back', 'zain', '...*teen.*', '...तीन।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Doosron ka reaction nahi. *Apni plate dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Doosron ka reaction nahi. Apni plate dekho. *Order se pehle.*', 'दूसरों का रिएक्शन नहीं। अपनी प्लेट देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'sara', 'Apni plate... *table pe?*', 'अपनी प्लेट... टेबल पे?'),
    try2: L('try2', 'hamza', 'Wow! Main bhi *react* karun?', 'वाओ! मैं भी रिएक्ट करूँ?'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... react mat karo. *Share karo.*', 'और तुम... रिएक्ट मत करो। शेयर करो।'),
    sweet: L('sweet', 'ayesha', 'Mera reaction? *Khana thanda ho raha hai.*', 'मेरा रिएक्शन? खाना ठंडा हो रहा है।'),
  },
  'extra-drama-queen': {
    room: 'Extra', file: 'table-extra-drama-queen', holder: null, burger: true,
    guest: { name: 'Drama Queen', seed: 'DramaQueen', voice: ['hf_alpha', 0.96, 0.85], look: { head: ['longCurly'], skinColor: ['f2d3b1'], clothingColor: ['8e3b8e'] } },
    victim: 'guest', panicker: 'hamza', objector: 'sara', solvers: ['zain', 'hamza'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Jab burger chhota ho aur dost *drama* kare',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo har plate pe *drama* karti hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Ye burger nahi... *mera toota hua dil hai.*', 'ये बर्गर नहीं... मेरा टूटा हुआ दिल है।'),
      L('s2', 'guest', 'Menu pe itna bara tha... *aur zindagi mein itna chhota.*', 'मेन्यू पे इतना बड़ा था... और ज़िंदगी में इतना छोटा।'),
      L('s3', 'zain', 'Behen, *burger hai, shaadi nahi toot rahi.*', 'बहन, बर्गर है, शादी नहीं टूट रही।'),
    ],
    panic: L('panic', 'hamza', 'Ek drama kam tha? *Ab doosra!*', 'एक ड्रामा कम था? अब दूसरा!'),
    scoldA: L('scoldA', 'madam', 'Menu ki photo pe *itna bharosa?*', 'मेन्यू की फ़ोटो पे इतना भरोसा?'),
    scoldB: L('scoldB', 'madam', 'Aansu band! *Class se bahar!*', 'आँसू बंद! क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *acting achi thi!*', 'यार, एक्टिंग अच्छी थी!'),
    back: L('back', 'sara', '...thori *over thi.*', '...थोड़ी ओवर थी।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Aansu nahi. *Asli size dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Aansu nahi. Asli size dekho. *Order se pehle.*', 'आँसू नहीं। असली साइज़ देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'zain', 'Matlab dil *tootne se pehle...*', 'मतलब दिल टूटने से पहले...'),
    try2: L('try2', 'hamza', '...plate *dekh lo!*', '...प्लेट देख लो!'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... dil mat todo. *QR scan karo.*', 'और तुम... दिल मत तोड़ो। क्यूआर स्कैन करो।'),
    sweet: L('sweet', 'ayesha', 'Tissue chahiye? Aur *ketchup* bhi?', 'टिशू चाहिए? और केचप भी?'),
  },
  'extra-camera-cousin': {
    room: 'Extra', file: 'table-extra-camera-cousin', holder: null, burger: true,
    guest: { name: 'Camera Cousin', seed: 'CameraCousin', voice: ['hm_omega', 1.1, 1.1], look: { head: ['hatHip'], skinColor: ['c58c5c'], clothingColor: ['3b7a57'] } },
    victim: 'guest', panicker: 'zain', objector: 'sara', solvers: ['hamza', 'sara'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Har group mein ek *"pehle photo"* wala hota hai',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo khane se *pehle photo* leta hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Koi haath nahi lagayega! *Pehle photo!*', 'कोई हाथ नहीं लगाएगा! पहले फ़ोटो!'),
      L('s2', 'guest', 'Thora left... light... *bas ek aur!*', 'थोड़ा लेफ़्ट... लाइट... बस एक और!'),
      L('s3', 'hamza', 'Bhai, burger *thanda* ho gaya.', 'भाई, बर्गर ठंडा हो गया।'),
    ],
    panic: L('panic', 'zain', 'Ayesha, *photo mein mat aana!*', 'आयशा, फ़ोटो में मत आना!'),
    scoldA: L('scoldA', 'madam', 'Photo pe photo? *Plate ka size pata hai?*', 'फ़ोटो पे फ़ोटो? प्लेट का साइज़ पता है?'),
    scoldB: L('scoldB', 'madam', 'Phone neeche! *Class se bahar!*', 'फ़ोन नीचे! क्लास से बाहर!'),
    object: L('object', 'sara', 'Yaar, *aesthetic* acha tha!', 'यार, एस्थेटिक अच्छा था!'),
    back: L('back', 'sara', '...khana *acha nahi tha.*', '...खाना अच्छा नहीं था।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Photo nahi. *Asli plate dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Photo nahi. Asli plate dekho. *Order se pehle.*', 'फ़ोटो नहीं। असली प्लेट देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'hamza', 'Matlab photo *order se pehle?*', 'मतलब फ़ोटो ऑर्डर से पहले?'),
    try2: L('try2', 'sara', 'Aur wo bhi *3D* mein...', 'और वो भी थ्री डी में...'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... photo baad mein. *Pehle plate dekho.*', 'और तुम... फ़ोटो बाद में। पहले प्लेट देखो।'),
    sweet: L('sweet', 'ayesha', 'Achha... ab ek *selfie* ho jaye?', 'अच्छा... अब एक सेल्फ़ी हो जाए?'),
  },
};
