// Bonus "Madam ki Class: Table Edition" episodes for after launch (5 Oct 2026 onwards), so Madam can name the lesson.
// Guests are ORIGINAL parody types (a food vlogger, etc.), never copies of real people: no real names, faces,
// voices or catchphrases. Claims stay honest: MENVA shows real dishes in 3D at partner restaurants, via the table QR.
const L = (id, who, say, hi) => ({ id, who, say, hi });

export const EXTRAS = {
  'extra-foodie-bhai': {
    room: 'Extra', file: 'table-extra-foodie-bhai', holder: null, burger: true,
    guest: { name: 'Foodie Bhai', seed: 'FoodieBhai', voice: ['hm_psi', 1.08, 1.12], look: { head: ['short5'], skinColor: ['c58c5c'], clothingColor: ['e8a33d'], accessories: ['sunglasses'], accessoriesProbability: 100 } },
    victim: 'guest', panicker: 'sara', objector: 'hamza', solvers: ['zain', 'hamza'], punish: 'out',
    prop: { label: '', html: '' },
    headline: 'Jab *food vlogger* chakhe baghair review kare',
    rewindText: '15 second pehle...',
    cta: { big: 'Us dost ko bhejo jo *review* dekh ke order karta hai.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'guest', 'Guys! Aaj hum aaye hain *sab se jumbo* burger pe!', 'गाइज़! आज हम आए हैं सबसे जंबो बर्गर पे!'),
      L('s2', 'guest', 'Size dekho! *Eleven out of ten!*', 'साइज़ देखो! इलेवन आउट ऑफ़ टेन!'),
      L('s3', 'zain', 'Bhai... tu ne *chakha* bhi nahi.', 'भाई... तूने चखा भी नहीं।'),
    ],
    panic: L('panic', 'sara', 'Ayesha, *mehmaan hain, chhod do!*', 'आयशा, मेहमान हैं, छोड़ दो!'),
    scoldA: L('scoldA', 'madam', 'Chakhe baghair *eleven out of ten?*', 'चखे बग़ैर इलेवन आउट ऑफ़ टेन?'),
    scoldB: L('scoldB', 'madam', 'Camera band! *Class se bahar!*', 'कैमरा बंद! क्लास से बाहर!'),
    object: L('object', 'hamza', 'Yaar, uske *followers* hain!', 'यार, उसके फ़ॉलोअर्स हैं!'),
    back: L('back', 'hamza', '...do *sau.*', '...दो सौ।'),
    saza: L('saza', 'madam', 'Aaj ka lesson *likho.*', 'आज का लेसन लिखो।'),
    lesson: { h: 'Review nahi. *Asli plate dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Review nahi. Asli plate dekho. *Order se pehle.*', 'रिव्यू नहीं। असली प्लेट देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'zain', 'Matlab... *table pe asli size?*', 'मतलब... टेबल पे असली साइज़?'),
    try2: L('try2', 'hamza', 'To pehle hi *bata deti!*', 'तो पहले ही बता देती!'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... QR scan karo. *Plate dekho.* Phir order.', 'और तुम... क्यूआर स्कैन करो। प्लेट देखो। फिर ऑर्डर।'),
    sweet: L('sweet', 'ayesha', 'Foodie bhai? Burger *thanda* ho raha hai.', 'फ़ूडी भाई? बर्गर ठंडा हो रहा है।'),
  },
  'extra-har-hafte': {
    room: 'Extra', file: 'table-extra-har-hafte', holder: null,
    victim: 'hamza', panicker: 'hamza', objector: 'sara', solvers: ['zain', 'hamza'], punish: 'duck',
    prop: { label: '', html: '' },
    headline: 'Har hafte *yahi* hota hai',
    rewindText: '20 second pehle...',
    cta: { big: 'Apne group ki *Ayesha* ko bhejo.', small: 'MENVA: partner restaurants pe table ka QR scan karo, asli dish 3D mein dekho, phir order karo.' },
    setup: [
      L('s1', 'hamza', 'Guys, *pata hai* har hafte kya hota hai?', 'गाइज़, पता है हर हफ़्ते क्या होता है?'),
      L('s2', 'zain', 'Kuch ghalat aata hai. *Ayesha chashma pehenti hai...*', 'कुछ ग़लत आता है। आयशा चश्मा पहनती है...'),
      L('s3', 'sara', '...aur hum log *saza* khaate hain.', '...और हम लोग सज़ा खाते हैं।'),
    ],
    panic: L('panic', 'hamza', 'Aur wo *abhi* ho raha hai.', 'और वो अभी हो रहा है।'),
    scoldA: L('scoldA', 'madam', 'Mere baare mein *reel bana rahe ho?*', 'मेरे बारे में रील बना रहे हो?'),
    scoldB: L('scoldB', 'madam', '*Murga* ban jao!', 'मुर्गा बन जाओ!'),
    object: L('object', 'sara', 'Yaar, reel *pachaas second* ki hai, log skip kar denge!', 'यार, रील पचास सेकंड की है, लोग स्किप कर देंगे!'),
    back: L('back', 'sara', '...tum log *mat karna.*', '...तुम लोग मत करना।'),
    saza: L('saza', 'madam', 'Skip kiya? *Absent!* Aaj ka lesson likho.', 'स्किप किया? एब्सेंट! आज का लेसन लिखो।'),
    lesson: { h: 'Reel poori dekho. *Plate poori dekho.* Order se pehle.', b: 'Partner restaurants pe: table ka QR, asli dish, *3D mein.*' },
    read: [L('read', 'madam', 'Reel poori dekho. Plate poori dekho. *Order se pehle.*', 'रील पूरी देखो। प्लेट पूरी देखो। ऑर्डर से पहले।')],
    try1: L('try1', 'zain', 'Ye... *ad hai kya?*', 'ये... ऐड है क्या?'),
    try2: L('try2', 'hamza', 'Haan, *thora sa...*', 'हाँ, थोड़ा सा...'),
    chup: L('chup', 'madam', '*Chup!*', 'चुप!'),
    fourth: L('fourth', 'madam', 'Aur tum... jo abhi skip karne wale the. *Share karo.*', 'और तुम... जो अभी स्किप करने वाले थे। शेयर करो।'),
    sweet: L('sweet', 'ayesha', 'Kya? Main to *bas khana dekh rahi thi.*', 'क्या? मैं तो बस खाना देख रही थी।'),
  },
};
