// Copies the public site into dist/ — the only folder Netlify publishes.
// Nothing is bundled or transformed: files are copied as-is, except the service
// worker, which gets a build id so each deploy refreshes its CSS/JS cache.
//
// Usage: npm run build

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

// Everything public. Anything not listed here (CLAUDE.md, scripts/, incoming-models/, data/dishes.csv, …) stays private.
// robots.txt is not copied — it's generated fresh below (needs the site origin for the Sitemap line).
const PUBLIC = ['index.html', 'sw.js', 'css', 'js', 'assets', 'vendor', 'stats'];
// Published under a different path than the source: Netlify's drag-and-drop upload skipped the
// data/build/ folder, which left the live site without its menu.
const RENAMED = { 'data/build/dishes.json': 'data/menu.json' };

fs.rmSync(DIST, { recursive: true, force: true });
const hash = crypto.createHash('sha256');
let count = 0;

function copy(rel, dest = rel) {
  const from = path.join(ROOT, rel);
  if (!fs.existsSync(from)) return;
  if (fs.statSync(from).isDirectory()) {
    for (const name of fs.readdirSync(from).sort()) copy(path.join(rel, name));
    return;
  }
  if (path.basename(rel) === 'meta.json') return; // pipeline internals, read by build-data only
  const to = path.join(DIST, dest);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  hash.update(rel).update(fs.readFileSync(from));
  count++;
}

if (!fs.existsSync(path.join(ROOT, 'vendor', 'model-viewer.min.js'))) {
  console.error('vendor/ is missing — run `npm run vendor` first.');
  process.exit(1);
}
PUBLIC.forEach((rel) => copy(rel));
for (const [from, to] of Object.entries(RENAMED)) {
  if (!fs.existsSync(path.join(ROOT, from))) { console.error(`${from} is missing — run npm run build-data.`); process.exit(1); }
  copy(from, to);
}

// Restaurant list, reused below for per-page SEO tags, noindex headers, redirects and the sitemap.
const dishesPath = path.join(ROOT, 'data', 'build', 'dishes.json');
if (!fs.existsSync(dishesPath)) { console.error(`${dishesPath} is missing — run npm run build-data.`); process.exit(1); }
const { restaurants } = JSON.parse(fs.readFileSync(dishesPath, 'utf8'));

// ═══ SEO: static per-page <head> tags ═══════════════════════════════════════
// Crawlers for link previews (WhatsApp, Facebook, X, LinkedIn, iMessage) and search engines do not
// run JavaScript, so every URL must return its own title/description/OG/canonical in the raw HTML.

// Site origin for absolute URLs: data/site.json's `domain` once the custom domain is live, else
// SITE_URL env var (Cloudflare or explicit), else Netlify's URL env var, else the known fallback.
const site = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'site.json'), 'utf8'));
let origin, originSource;
if (site.domain) { origin = `https://${site.domain}`; originSource = 'data/site.json domain'; }
else if (process.env.SITE_URL) { origin = process.env.SITE_URL.replace(/\/+$/, ''); originSource = 'process.env.SITE_URL'; }
else if (process.env.URL) { origin = process.env.URL.replace(/\/+$/, ''); originSource = 'process.env.URL'; }
else { origin = 'https://menva-ar.netlify.app'; originSource = 'https://menva-ar.netlify.app'; }
console.log(`SEO: site origin ${origin} (source: ${originSource})`);

const THEME_PAPER = { default: '#EFEBE2', gauchos: '#EFEBE2', baraza: '#FAF5EC' };

const escAttr = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
// Content-hash query param so WhatsApp/Facebook's aggressive image cache busts whenever the image
// itself changes (they cache by URL, not by content).
const assetVersion = (relPath) => {
  const full = path.join(DIST, relPath);
  if (!fs.existsSync(full)) return '0';
  return crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex').slice(0, 10);
};
// </script>-safe JSON-LD: a non-executable script type (application/ld+json is not JS-typed, so
// the CSP script-src directive never applies to it — no console error to watch for there).
const jsonLdScript = (obj) => `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, '\\u003c')}</script>`;

function renderHead({ title, description, canonical, image, imageAlt, themeColor, noindex, jsonLd }) {
  const lines = [
    '<!-- SEO:BEGIN — generated by scripts/build.mjs; edit the generator, not this file -->',
    `<title>${escAttr(title)}</title>`,
    `<meta name="description" content="${escAttr(description)}">`,
    `<link rel="canonical" href="${escAttr(canonical)}">`,
  ];
  if (noindex) lines.push('<meta name="robots" content="noindex, nofollow">');
  lines.push(
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="MENVA">',
    `<meta property="og:title" content="${escAttr(title)}">`,
    `<meta property="og:description" content="${escAttr(description)}">`,
    `<meta property="og:url" content="${escAttr(canonical)}">`,
    `<meta property="og:image" content="${escAttr(image)}">`,
    `<meta property="og:image:secure_url" content="${escAttr(image)}">`,
    '<meta property="og:image:type" content="image/jpeg">',
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    `<meta property="og:image:alt" content="${escAttr(imageAlt)}">`,
    '<meta property="og:locale" content="en_US">',
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escAttr(title)}">`,
    `<meta name="twitter:description" content="${escAttr(description)}">`,
    `<meta name="twitter:image" content="${escAttr(image)}">`,
    `<meta name="theme-color" content="${escAttr(themeColor)}">`,
    '<link rel="icon" href="/favicon.ico" sizes="32x32">',
    '<link rel="icon" href="/assets/social/favicon.svg" type="image/svg+xml">',
    '<link rel="apple-touch-icon" href="/assets/social/apple-touch-icon.png">',
    '<link rel="manifest" href="/site.webmanifest">',
    ...jsonLd.map(jsonLdScript),
    '<!-- SEO:END -->',
  );
  return lines.join('\n  ');
}

const SEO_BLOCK_RE = /<!-- SEO:BEGIN[\s\S]*?<!-- SEO:END -->/;
function withHead(html, headBlock) {
  if (!SEO_BLOCK_RE.test(html)) { console.error('index.html is missing the <!-- SEO:BEGIN/END --> markers.'); process.exit(1); }
  return html.replace(SEO_BLOCK_RE, headBlock);
}

const baseHtml = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8');

// ── Home ──
const homeImageRel = 'assets/social/og-menva.jpg';
const homeImage = `${origin}/${homeImageRel}?v=${assetVersion(homeImageRel)}`;
const homeHead = renderHead({
  title: 'MENVA — See it before you order it',
  description: 'See real dishes in 3D and AR before you order. Scan the QR at your table and MENVA brings the menu to life — no app to install.',
  canonical: `${origin}/`,
  image: homeImage,
  imageAlt: 'MENVA — see real dishes in 3D and AR on your table.',
  themeColor: THEME_PAPER.default,
  noindex: false,
  jsonLd: [
    { '@context': 'https://schema.org', '@type': 'Organization', name: 'MENVA', url: `${origin}/`, logo: `${origin}/assets/logo.svg` },
    { '@context': 'https://schema.org', '@type': 'WebSite', name: 'MENVA', url: `${origin}/` },
  ],
});
fs.writeFileSync(path.join(DIST, 'index.html'), withHead(baseHtml, homeHead));

// ── Per restaurant ── (dist/<slug>/index.html; table URLs /<slug>/12 canonicalise to /<slug>)
for (const r of restaurants) {
  const imageRel = `assets/social/og-${r.id}.jpg`;
  const image = fs.existsSync(path.join(DIST, imageRel))
    ? `${origin}/${imageRel}?v=${assetVersion(imageRel)}`
    : homeImage; // no share image generated for this restaurant yet — fall back rather than 404
  const lede = (r.tagline || r.description || '').trim();
  let description = lede ? `${lede.replace(/\.?$/, '.')} See every dish on your table before you order.` : 'See every dish on your table before you order.';
  if (description.length > 160) description = description.slice(0, 157).trimEnd() + '…';
  const canonical = `${origin}/${r.slug}`;

  const address = { '@type': 'PostalAddress', addressCountry: 'PK' };
  if (r.address) address.streetAddress = r.address;
  if (r.location) address.addressLocality = r.location;
  const restaurantLd = { '@context': 'https://schema.org', '@type': 'Restaurant', name: r.name, url: canonical, image };
  if (r.cuisine) restaurantLd.servesCuisine = r.cuisine;
  if (r.address || r.location) restaurantLd.address = address;
  if (r.hours === 'Open 24/7') restaurantLd.openingHours = 'Mo-Su 00:00-24:00';
  if (r.website) restaurantLd.sameAs = [r.website];

  const head = renderHead({
    title: `${r.name} — menu in 3D · MENVA`,
    description,
    canonical,
    image,
    imageAlt: `${r.name} — see the menu in 3D on your table.`,
    themeColor: THEME_PAPER[r.theme] || THEME_PAPER.default,
    noindex: r.listed !== true,
    jsonLd: [restaurantLd],
  });
  const outPath = path.join(DIST, r.slug, 'index.html');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, withHead(baseHtml, head));
}

// Drag-and-drop deploys ignore netlify.toml, so mirror its headers/redirects as _headers/_redirects.
const headers = [], redirects = [];
let block = null;
for (const line of fs.readFileSync(path.join(ROOT, 'netlify.toml'), 'utf8').split('\n')) {
  const t = line.trim();
  if (t === '[[headers]]') { block = { kind: 'h', values: [] }; headers.push(block); continue; }
  if (t === '[[redirects]]') { block = { kind: 'r' }; redirects.push(block); continue; }
  if (t.startsWith('[') && t !== '[headers.values]') { block = null; continue; }
  const m = t.match(/^([\w-]+)\s*=\s*"?(.*?)"?$/);
  if (!block || !m) continue;
  if (block.kind === 'h') m[1] === 'for' ? (block.for = m[2]) : block.values.push(`${m[1]}: ${m[2]}`);
  else block[m[1]] = m[2];
}

// Pitch demos: a restaurant not yet public (listed !== true, e.g. Baraza) gets noindex on its
// pages, so a private client demo can never be indexed or found before it's approved to go live.
for (const r of restaurants) {
  if (r.listed === true) continue;
  for (const pattern of [`/${r.slug}`, `/${r.slug}/*`]) headers.push({ kind: 'h', for: pattern, values: ['X-Robots-Tag: noindex, nofollow'] });
}
fs.writeFileSync(path.join(DIST, '_headers'), headers.map((h) => `${h.for}\n${h.values.map((v) => `  ${v}`).join('\n')}`).join('\n\n') + '\n');
fs.writeFileSync(path.join(DIST, '_redirects'), redirects.map((r) => `${r.from}  ${r.to}  ${r.status}`).join('\n') + '\n');

// Browsers request /favicon.ico at the site root regardless of what any <link> tag says.
copy('assets/social/favicon.ico', 'favicon.ico');

const build = hash.digest('hex').slice(0, 12);

// Stamp local CSS/JS links with the build id. HTML is always revalidated, so after a deploy the
// page asks for new URLs and the service worker can never pair old JavaScript with new data.
for (const page of ['index.html', 'stats/index.html', ...restaurants.map((r) => `${r.slug}/index.html`)]) {
  const file = path.join(DIST, page);
  if (!fs.existsSync(file)) continue;
  const html = fs.readFileSync(file, 'utf8').replace(/((?:href|src)="\/(?:css|js|stats)\/[^"?]+\.(?:css|js))"/g, `$1?v=${build}"`);
  fs.writeFileSync(file, html);
}
const swPath = path.join(DIST, 'sw.js');
fs.writeFileSync(swPath, fs.readFileSync(swPath, 'utf8').replace('__BUILD__', build));

// ═══ SEO: manifest, robots.txt, sitemap.xml, root favicon ═══════════════════
fs.writeFileSync(path.join(DIST, 'site.webmanifest'), JSON.stringify({
  name: 'MENVA',
  short_name: 'MENVA',
  icons: [
    { src: '/assets/social/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: '/assets/social/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: '/assets/social/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
  theme_color: '#1A1714',
  background_color: '#EFEBE2',
  display: 'standalone',
  start_url: '/',
}, null, 2) + '\n');

fs.writeFileSync(path.join(DIST, 'robots.txt'),
  'User-agent: *\nAllow: /\nDisallow: /stats\nDisallow: /api/\n\n' +
  `Sitemap: ${origin}/sitemap.xml\n`);

const lastmod = new Date().toISOString().slice(0, 10);
const sitemapUrls = [origin + '/', ...restaurants.filter((r) => r.listed === true).map((r) => `${origin}/${r.slug}`)];
fs.writeFileSync(path.join(DIST, 'sitemap.xml'),
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  sitemapUrls.map((u) => `  <url><loc>${escAttr(u)}</loc><lastmod>${lastmod}</lastmod></url>`).join('\n') + '\n' +
  '</urlset>\n');

console.log(`dist/: ${count} files, build ${build}`);
